name: Notify Discord on New Post

on:
  push:
    branches:
      - master  # Change this to your default branch if it's different

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Notification
        run: |
          # Fetch the RSS feed
          RSS_FEED_URL="https://lexi.lat/feed.xml"  # Replace with your RSS feed URL
          LATEST_POST_URL=$(curl -s "$RSS_FEED_URL" | grep -oP '(?<=<link>).*?(?=</link>)' | head -n 1)

          # Send the notification to Discord
          curl -X POST -H "Content-Type: application/json" -d "{\"content\": \"Alexia acaba de publicar un nuevo artículo! Leelo aquí: $LATEST_POST_URL\"}" https://discord.com/api/webhooks/1395954872989520053/3ftU7hAUSz2uI7D4QvDcGmgfXacSvdW-9_m1PLaOBHa3ylf_JKls_AS__ecOe8Y_eHol  # Replace with your Discord webhook URL
